server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task
    username: admin
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: true